name: Lint & Test Package

on: push

jobs:
    build:
  
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.x"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install ruff pytest
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        - name: Lint with ruff
          run: |
            # stop the build if there are Python syntax errors or undefined names
            ruff --format=github --select=E9,F63,F7,F82 --line-length=100 --target-version=py37 .
            # default set of ruff rules with GitHub Annotations
            ruff --format=github --line-length=100 --target-version=py37 .
        - name: Install the local package
          run: |
            python3 -m pip install .
        - name: Test with pytest
          run: |
            pytest tests\